# Generated by Django 4.2 on 2024-11-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razon',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
