# Generated by Django 4.2 on 2024-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratios', '0002_razon_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razon',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
