# Generated by Django 4.2 on 2024-11-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_clave_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
