# Generated by Django 4.2 on 2024-11-01 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBalance',
            fields=[
                ('idCuentaBalance', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=25)),
                ('nombre', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('idBalance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='balance.balance')),
            ],
            options={
                'db_table': 'cuentabalance',
                'managed': True,
            },
        ),
    ]
