# Generated by Django 4.2 on 2024-11-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaResultado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaresultado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
