# Generated by Django 4.2 on 2024-11-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
    ]
